
 export const CREATE_TWEET_REQUEST = "CREATE_TWEET_REQUEST"
export const CREATE_TWEET_SUCCESS = "CREATE_TWEET_SUCCESS"
export const CREATE_TWEET_FAIL = "CREATE_TWEET_FAIL"
export const CREATE_TWEET_RESET = "CREATE_TWEET_RESET"

export const LIKE_TWEET = "LIKE_TWEET"
export const UNLIKE_TWEET = "UNLIKE_TWEET"

export const GET_TWEET_LIKES = "GET_TWEET_LIKES"

export const GET_TWEETS_REQUEST = "GET_TWEETS_REQUEST"
export const GET_TWEETS_SUCCESS = "GET_TWEETS_SUCCESS"
export const GET_TWEETS_FAIL = "GET_TWEETS_FAIL"

export const GET_PROFILE_TWEETS_REQUEST = "GET_PROFILE_TWEETS_REQUEST"
export const GET_PROFILE_TWEETS_SUCCESS = "GET_PROFILE_TWEETS_SUCCESS"
export const GET_PROFILE_TWEETS_FAIL = "GET_PROFILE_TWEETS_FAIL"

export const DELETE_TWEET_REQUEST = "DELETE_TWEET_REQUEST"
export const DELETE_TWEET_SUCCESS = "DELETE_TWEET_SUCCESS"
export const DELETE_TWEET_FAIL = "DELETE_TWEET_FAIL"
