

export const PROFILE_SAVE_REQUEST = "PROFILE_SAVE_REQUEST"
export const PROFILE_SAVE_SUCCESS = "PROFILE_SAVE_SUCCESS"
export const PROFILE_SAVE_FAIL = "PROFILE_SAVE_FAIL"


export const PROFILE_INFO_REQUEST = "PROFILE_INFO_REQUEST"
export const PROFILE_INFO_SUCCESS = "PROFILE_INFO_SUCCESS"
export const PROFILE_INFO_FAIL = "PROFILE_INFO_FAIL"